WITH claims_intermediate AS (
    SELECT 
		MD.DSRC_NM AS DSRC_NM, 
        	MD.MRKT_NM AS MRKT_NM, 
		MD.INDC_NM AS INDC_NM, 
		CLAIM_IDENTIFIER AS CLM_ID,
		PATIENT_IDENTIFIER AS PAT_ID,
        	PD.PATIENT_YOB AS PAT_YR_OF_BRTH, 
        	PD.PATIENT_GENDER AS PAT_GNDR_NM,
        	PRIMARY_PATIENT_PLAN_IDENTIFIER AS PAT_PMY_PLAN_ID,
        	SECONDARY_PATIENT_PLAN_IDENTIFIER AS PAT_SECDY_PLAN_ID,
		t.RENDERING_PHYSICIAN_NPI AS RD_PHYN_NPI,
		t.REFERRING_PHYSICIAN_NPI AS RFER_PHYN_NPI,
		t.BILLING_PHYSICIAN_NPI AS BILL_PHYN_NPI,
		t.PRESCRIBER_PHYSICIAN_NPI AS PRSB_PHYN_NPI, 
		t.PHARMACY_PHYSICIAN_NPI AS PHRM_PHYN_NPI,
		cc2.CUSTOMER_IDENTIFIER AS RD_PHYN_ALEXION_ID,
		cc1.CUSTOMER_IDENTIFIER AS RFER_PHYN_ALEXION_ID, 
		cc3.CUSTOMER_IDENTIFIER AS BILL_PHYN_ALEXION_ID,
		cc4.CUSTOMER_IDENTIFIER AS PRSB_PHYN_ALEXION_ID,
		cc5.CUSTOMER_IDENTIFIER AS PHRM_PHYN_ALEXION_ID, 
		EVENT_DATE AS EVNT_DT,
		EVENT_TO_DATE AS EVNT_TO_DT,
		MD.EVNT_CD AS EVNT_CD,
        	MD.EVNT_TYP_NM AS EVNT_TYP_NM, 
        	MD.EVNT_CLSS_NM AS EVNT_CLSS_NM, 
        	MD.EVNT_SUB_CLSS_NM AS EVNT_SUB_CLSS_NM, 
        	MD.EVNT_DSC AS EVNT_DSC, 
		VISIT_TYPE AS VST_TYP_NM,
		PLACE_OF_SERVICE_NAME AS PLACE_OF_SERV_NM,
		DAYS_ON_THERAPY AS DAYS_ON_TRPY,
        	'' AS DSG_STRN_QTY, 
        	OUT_OF_POCKET_PAID_AMOUNT AS OUT_OF_POCKT_PAID_AMT,
        	DRUG_LOOKFORWARD_DAYS AS DRUG_LOOKFORWARD_DAYS,
        	CLAIM_STATUS AS CLM_STAT,
        	CURRENT_TIMESTAMP AS LOAD_DT
    FROM (
        -- Union of multiple event queries
(
  Select PATIENT_IDENTIFIER, CLAIM_IDENTIFIER, EVENT_DATE, EVENT_TO_DATE, EVENT_CODE, RENDERING_PHYSICIAN_NPI, REFERRING_PHYSICIAN_NPI, BILLING_PHYSICIAN_NPI, PRESCRIBER_PHYSICIAN_NPI, PHARMACY_PHYSICIAN_NPI, PLACE_OF_SERVICE_NAME, DAYS_ON_THERAPY, OUT_OF_POCKET_PAID_AMOUNT, CLAIM_STATUS, SECONDARY_PATIENT_PLAN_IDENTIFIER, PRIMARY_PATIENT_PLAN_IDENTIFIER, VISIT_TYPE from 
(
select MEDICAL_EVENT_ID as CLAIM_IDENTIFIER, KH_PLAN_ID as PRIMARY_PATIENT_PLAN_IDENTIFIER, RENDERING_NPI as RENDERING_PHYSICIAN_NPI, REFERRING_NPI as REFERRING_PHYSICIAN_NPI, BILLING_NPI as BILLING_PHYSICIAN_NPI, CAST(NULL AS STRING) AS PRESCRIBER_PHYSICIAN_NPI,  CAST(NULL AS STRING) AS PHARMACY_PHYSICIAN_NPI, SERVICE_DATE as EVENT_DATE, PLACE_OF_SERVICE as PLACE_OF_SERVICE_NAME, CAST(NULL AS STRING) AS DAYS_ON_THERAPY, CAST(NULL AS STRING) AS OUT_OF_POCKET_PAID_AMOUNT, PROCEDURE_CODE as EVENT_CODE, NDC11, PATIENT_ID as PATIENT_IDENTIFIER, SERVICE_TO_DATE as EVENT_TO_DATE, CAST(NULL AS STRING) AS SECONDARY_PATIENT_PLAN_IDENTIFIER,VISIT_TYPE, 'PAID' as CLAIM_STATUS from ALXN_POC.MEDICAL_EVENTS))
union 
(select
PATIENT_IDENTIFIER, CLAIM_IDENTIFIER, EVENT_DATE, EVENT_TO_DATE, EVENT_CODE, RENDERING_PHYSICIAN_NPI, REFERRING_PHYSICIAN_NPI, BILLING_PHYSICIAN_NPI, PRESCRIBER_PHYSICIAN_NPI, PHARMACY_PHYSICIAN_NPI, PLACE_OF_SERVICE_NAME, DAYS_ON_THERAPY, OUT_OF_POCKET_PAID_AMOUNT, CLAIM_STATUS, SECONDARY_PATIENT_PLAN_IDENTIFIER, PRIMARY_PATIENT_PLAN_IDENTIFIER, VISIT_TYPE 
from
(
  select MEDICAL_EVENT_ID as CLAIM_IDENTIFIER, KH_PLAN_ID as PRIMARY_PATIENT_PLAN_IDENTIFIER, RENDERING_NPI as RENDERING_PHYSICIAN_NPI, REFERRING_NPI as REFERRING_PHYSICIAN_NPI, BILLING_NPI as BILLING_PHYSICIAN_NPI, CAST(NULL AS STRING) AS PRESCRIBER_PHYSICIAN_NPI,  CAST(NULL AS STRING) AS PHARMACY_PHYSICIAN_NPI, SERVICE_DATE as EVENT_DATE, PLACE_OF_SERVICE as PLACE_OF_SERVICE_NAME, CAST(NULL AS STRING) AS DAYS_ON_THERAPY, CAST(NULL AS STRING) AS OUT_OF_POCKET_PAID_AMOUNT, PROCEDURE_CODE, NDC11 as EVENT_CODE, PATIENT_ID as PATIENT_IDENTIFIER, SERVICE_TO_DATE as EVENT_TO_DATE, CAST(NULL AS STRING) AS SECONDARY_PATIENT_PLAN_IDENTIFIER,VISIT_TYPE, 'PAID' as CLAIM_STATUS from ALXN_POC.MEDICAL_EVENTS))
union

(select PATIENT_IDENTIFIER, CLAIM_IDENTIFIER, EVENT_DATE, EVENT_TO_DATE, EVENT_CODE, RENDERING_PHYSICIAN_NPI, REFERRING_PHYSICIAN_NPI, BILLING_PHYSICIAN_NPI, PRESCRIBER_PHYSICIAN_NPI, PHARMACY_PHYSICIAN_NPI, PLACE_OF_SERVICE_NAME, DAYS_ON_THERAPY, OUT_OF_POCKET_PAID_AMOUNT,CLAIM_STATUS, SECONDARY_PATIENT_PLAN_IDENTIFIER, PRIMARY_PATIENT_PLAN_IDENTIFIER, VISIT_TYPE from
(
Select MEDICAL_EVENT_ID as CLAIM_IDENTIFIER, KH_PLAN_ID as PRIMARY_PATIENT_PLAN_IDENTIFIER, RENDERING_NPI as RENDERING_PHYSICIAN_NPI, REFERRING_NPI as REFERRING_PHYSICIAN_NPI, BILLING_NPI as BILLING_PHYSICIAN_NPI, CAST(NULL AS STRING) AS PRESCRIBER_PHYSICIAN_NPI,  CAST(NULL AS STRING) AS PHARMACY_PHYSICIAN_NPI, SERVICE_DATE as EVENT_DATE, PLACE_OF_SERVICE as PLACE_OF_SERVICE_NAME, CAST(NULL AS STRING) AS DAYS_ON_THERAPY, CAST(NULL AS STRING) AS OUT_OF_POCKET_PAID_AMOUNT, PROCEDURE_CODE, NDC11, PATIENT_ID as PATIENT_IDENTIFIER, SERVICE_TO_DATE as EVENT_TO_DATE, CAST(NULL AS STRING) AS SECONDARY_PATIENT_PLAN_IDENTIFIER,VISIT_TYPE, 'PAID' as CLAIM_STATUS, TRIM(VALUE) AS EVENT_CODE from ALXN_POC.MEDICAL_EVENTS, LATERAL FLATTEN(INPUT => SPLIT(DIAGNOSIS_CODES, '|')) WHERE DIAGNOSIS_CODES IS NOT NULL))
union
(select PATIENT_IDENTIFIER, CLAIM_IDENTIFIER, EVENT_DATE, EVENT_TO_DATE, EVENT_CODE, RENDERING_PHYSICIAN_NPI, REFERRING_PHYSICIAN_NPI, BILLING_PHYSICIAN_NPI, PRESCRIBER_PHYSICIAN_NPI, PHARMACY_PHYSICIAN_NPI, PLACE_OF_SERVICE_NAME, DAYS_ON_THERAPY, OUT_OF_POCKET_PAID_AMOUNT, CLAIM_STATUS, SECONDARY_PATIENT_PLAN_IDENTIFIER, PRIMARY_PATIENT_PLAN_IDENTIFIER, VISIT_TYPE from(
Select PHARMACY_EVENT_ID as CLAIM_IDENTIFIER, FILL_DATE as EVENT_DATE, CAST(NULL AS STRING) as BILLING_PHYSICIAN_NPI, CAST(NULL AS STRING) as RENDERING_PHYSICIAN_NPI, PHARMACY_NPI as PHARMACY_PHYSICIAN_NPI, PRESCRIBER_NPI AS PRESCRIBER_PHYSICIAN_NPI, DAYS_SUPPLY as DAYS_ON_THERAPY, PATIENT_OOP as OUT_OF_POCKET_PAID_AMOUNT, CAST(NULL AS STRING) AS REFERRING_PHYSICIAN_NPI, CAST(NULL AS STRING) AS PLACE_OF_SERVICE_NAME, PRIMARY_KH_PLAN_ID as PRIMARY_PATIENT_PLAN_IDENTIFIER, SECONDARY_KH_PLAN_ID as SECONDARY_PATIENT_PLAN_IDENTIFIER, NDC11, PATIENT_ID as PATIENT_IDENTIFIER, CAST(NULL AS STRING) AS EVENT_TO_DATE, TRANSACTION_RESULT as CLAIM_STATUS, DIAGNOSIS_CODE as EVENT_CODE, 'Pharmacy' AS VISIT_TYPE 
from ALXN_POC.PHARMACY_EVENTS))
union
(select PATIENT_IDENTIFIER, CLAIM_IDENTIFIER, EVENT_DATE, EVENT_TO_DATE, EVENT_CODE, RENDERING_PHYSICIAN_NPI, REFERRING_PHYSICIAN_NPI, BILLING_PHYSICIAN_NPI, PRESCRIBER_PHYSICIAN_NPI, PHARMACY_PHYSICIAN_NPI, PLACE_OF_SERVICE_NAME, DAYS_ON_THERAPY, OUT_OF_POCKET_PAID_AMOUNT, CLAIM_STATUS, SECONDARY_PATIENT_PLAN_IDENTIFIER, PRIMARY_PATIENT_PLAN_IDENTIFIER, VISIT_TYPE 
from(
Select PHARMACY_EVENT_ID as CLAIM_IDENTIFIER, FILL_DATE as EVENT_DATE, CAST(NULL AS STRING) as BILLING_PHYSICIAN_NPI, CAST(NULL AS STRING) as RENDERING_PHYSICIAN_NPI, PHARMACY_NPI as PHARMACY_PHYSICIAN_NPI, PRESCRIBER_NPI as PRESCRIBER_PHYSICIAN_NPI, DAYS_SUPPLY as DAYS_ON_THERAPY, PATIENT_OOP as OUT_OF_POCKET_PAID_AMOUNT, CAST(NULL AS STRING) AS REFERRING_PHYSICIAN_NPI, CAST(NULL AS STRING) AS PLACE_OF_SERVICE_NAME, PRIMARY_KH_PLAN_ID as PRIMARY_PATIENT_PLAN_IDENTIFIER, SECONDARY_KH_PLAN_ID as SECONDARY_PATIENT_PLAN_IDENTIFIER, NDC11 as EVENT_CODE, PATIENT_ID as PATIENT_IDENTIFIER, CAST(NULL AS STRING) AS EVENT_TO_DATE, TRANSACTION_RESULT as CLAIM_STATUS, 'Pharmacy' AS VISIT_TYPE 
from ALXN_POC.PHARMACY_EVENTS))
    ) t
    LEFT JOIN (
        SELECT * 
        FROM ALXN_POC.CONFIG_MRKT_DEFN
         WHERE DSRC_NM = 'KOMODO' AND MRKT_NM = 'NEUROLOGY' AND INDC_NM = 'GMG'
    ) MD ON UPPER(t.EVENT_CODE) = UPPER(MD.EVNT_CD)
    LEFT JOIN ALXN_POC.PATIENT PD ON t.PATIENT_IDENTIFIER = PD.PATIENT_ID
    LEFT JOIN (SELECT * FROM ALXN_POC.CUSTOMER WHERE UPPER(STATUS_REASON)='ACTIVE' AND UPPER(CUSTOMER_TYPE)='HCP') cc1 ON t.REFERRING_PHYSICIAN_NPI = cc1.NPI
    LEFT JOIN (SELECT * FROM ALXN_POC.CUSTOMER WHERE UPPER(STATUS_REASON)='ACTIVE' AND UPPER(CUSTOMER_TYPE)='HCP') cc2 ON t.RENDERING_PHYSICIAN_NPI = cc2.NPI
    LEFT JOIN (SELECT * FROM ALXN_POC.CUSTOMER WHERE UPPER(STATUS_REASON)='ACTIVE' AND UPPER(CUSTOMER_TYPE)='HCP') cc3 ON t.BILLING_PHYSICIAN_NPI = cc3.NPI
    LEFT JOIN (SELECT * FROM ALXN_POC.CUSTOMER WHERE UPPER(STATUS_REASON)='ACTIVE' AND UPPER(CUSTOMER_TYPE)='HCP') cc4 ON t.PRESCRIBER_PHYSICIAN_NPI = cc4.NPI
    LEFT JOIN (SELECT * FROM ALXN_POC.CUSTOMER WHERE UPPER(STATUS_REASON)='ACTIVE' AND UPPER(CUSTOMER_TYPE)='HCP') cc5 ON t.PHARMACY_PHYSICIAN_NPI = cc5.NPI
)
SELECT * FROM claims_intermediate where CLM_STAT='PAID' 
