CREATE TABLE ALXN_POC.PATIENT_FLAG AS (
SELECT PAT_ID,RD_PHYN_NPI,RFER_PHYN_NPI,BILL_PHYN_NPI,
MAX(CASE WHEN EVNT_SUB_CLSS_NM='PRIMARY_DIAGNOSIS' THEN 1 ELSE 0 END) AS DIAG_FLAG,
MAX(CASE WHEN EVNT_TYP_NM='TREATMENT' THEN 1 ELSE 0 END) AS TRTMNT_FLAG,
MAX(CASE WHEN EVNT_CLSS_NM='INFECTION' THEN 1 ELSE 0 END) AS INFN_FLAG
FROM ALXN_POC.CONSOLIDATED_CLAIMS
GROUP BY 1,2,3,4
)
